SPOOL &pathforlog\COBRACacheDbDdlScript.log

-- DDL generated by Composite Studio (Fri Nov 27 06:38:08 CET 2015)
-- To cache resource '/shared/Applications/COBRA/RulesDB/personnel'
-- To data source '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB'
-- In table '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB/COBRA_CACHE/C_Cache_Personnel0'

DROP TABLE "COBRA_CACHE"."C_Cache_Personnel0";

CREATE TABLE "COBRA_CACHE"."C_Cache_Personnel0" (
	"user_name" VARCHAR2(8), 
	"HR_DB_NAME" VARCHAR2(16), 
	"FUNCTIONAL_TITLE" VARCHAR2(40 CHAR), 
	"PERS_CATEGORY" VARCHAR2(1), 
	"LC_STATE" VARCHAR2(10), 
	"LC_DATE" TIMESTAMP (9), 
	"HR_DB_SOURCE" VARCHAR2(40), 
	"HIRE_DATE_C" TIMESTAMP (9), 
	"JOB_HIRE_DATE" TIMESTAMP (9), 
	"TERMINATION_DATE" TIMESTAMP (9), 
	"DIV_BU_CODE" VARCHAR2(13), 
	"DIVISION_CODE" VARCHAR2(6), 
	"DIVISION_DESC" VARCHAR2(64), 
	"BUSINESS_UNIT_CODE" VARCHAR2(6), 
	"BUSINESS_UNIT_DESC" VARCHAR2(64), 
	"SECTOR_CODE" VARCHAR2(2), 
	"ORG_UNIT" VARCHAR2(2), 
	"DEPARTMENT_DESC" VARCHAR2(32 CHAR), 
	"REFERENCE" VARCHAR2(14), 
	"FUNCTION_CODE" VARCHAR2(8), 
	"FUNCTION_DESC" VARCHAR2(64), 
	"COST_CENTER_TYPE" VARCHAR2(8 CHAR), 
	"COST_CENTER_NUMBER" VARCHAR2(10 CHAR), 
	"SUPERVISOR_ID" VARCHAR2(8), 
	"COUNTRY_CODE" VARCHAR2(2), 
	"COUNTRY_NAME" VARCHAR2(25), 
	"WORLD_REGION" VARCHAR2(20), 
	"SITE_CODE" VARCHAR2(4), 
	"SITE_NAME" VARCHAR2(40), 
	"SITE_CODE_EXT" VARCHAR2(8), 
	"SITA_ORG_CODE" VARCHAR2(2), 
	"CD_ID" NUMBER(19,0), 
	"PHONE_COUNTRY_CODE" VARCHAR2(5), 
	"PHONE_AREA_CODE" VARCHAR2(6), 
	"VIP_STATUS" VARCHAR2(20), 
	"OPLEVEL3_CODE" VARCHAR2(40), 
	"OPLEVEL3_DESC" VARCHAR2(64), 
	"OPLEVEL2_CODE" VARCHAR2(40), 
	"OPLEVEL2_DESC" VARCHAR2(64), 
	"OPLEVEL1_CODE" VARCHAR2(40), 
	"OPLEVEL1_DESC" VARCHAR2(64), 
	"EMAIL_DOMAIN" VARCHAR2(50)
);


-- DDL generated by Composite Studio (Fri Nov 27 06:38:08 CET 2015)
-- To cache resource '/shared/Applications/COBRA/RulesDB/personnel'
-- To data source '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB'
-- In table '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB/COBRA_CACHE/C_Cache_Personnel1'

DROP TABLE "COBRA_CACHE"."C_Cache_Personnel1";

CREATE TABLE "COBRA_CACHE"."C_Cache_Personnel1" (
	"user_name" VARCHAR2(8), 
	"HR_DB_NAME" VARCHAR2(16), 
	"FUNCTIONAL_TITLE" VARCHAR2(40 CHAR), 
	"PERS_CATEGORY" VARCHAR2(1), 
	"LC_STATE" VARCHAR2(10), 
	"LC_DATE" TIMESTAMP (9), 
	"HR_DB_SOURCE" VARCHAR2(40), 
	"HIRE_DATE_C" TIMESTAMP (9), 
	"JOB_HIRE_DATE" TIMESTAMP (9), 
	"TERMINATION_DATE" TIMESTAMP (9), 
	"DIV_BU_CODE" VARCHAR2(13), 
	"DIVISION_CODE" VARCHAR2(6), 
	"DIVISION_DESC" VARCHAR2(64), 
	"BUSINESS_UNIT_CODE" VARCHAR2(6), 
	"BUSINESS_UNIT_DESC" VARCHAR2(64), 
	"SECTOR_CODE" VARCHAR2(2), 
	"ORG_UNIT" VARCHAR2(2), 
	"DEPARTMENT_DESC" VARCHAR2(32 CHAR), 
	"REFERENCE" VARCHAR2(14), 
	"FUNCTION_CODE" VARCHAR2(8), 
	"FUNCTION_DESC" VARCHAR2(64), 
	"COST_CENTER_TYPE" VARCHAR2(8 CHAR), 
	"COST_CENTER_NUMBER" VARCHAR2(10 CHAR), 
	"SUPERVISOR_ID" VARCHAR2(8), 
	"COUNTRY_CODE" VARCHAR2(2), 
	"COUNTRY_NAME" VARCHAR2(25), 
	"WORLD_REGION" VARCHAR2(20), 
	"SITE_CODE" VARCHAR2(4), 
	"SITE_NAME" VARCHAR2(40), 
	"SITE_CODE_EXT" VARCHAR2(8), 
	"SITA_ORG_CODE" VARCHAR2(2), 
	"CD_ID" NUMBER(19,0), 
	"PHONE_COUNTRY_CODE" VARCHAR2(5), 
	"PHONE_AREA_CODE" VARCHAR2(6), 
	"VIP_STATUS" VARCHAR2(20), 
	"OPLEVEL3_CODE" VARCHAR2(40), 
	"OPLEVEL3_DESC" VARCHAR2(64), 
	"OPLEVEL2_CODE" VARCHAR2(40), 
	"OPLEVEL2_DESC" VARCHAR2(64), 
	"OPLEVEL1_CODE" VARCHAR2(40), 
	"OPLEVEL1_DESC" VARCHAR2(64), 
	"EMAIL_DOMAIN" VARCHAR2(50)
);


-- DDL generated by Composite Studio (Fri Nov 27 06:38:08 CET 2015)
-- To cache resource '/shared/Applications/COBRA/RulesDB/personnel'
-- To data source '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB'
-- In table '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB/COBRA_CACHE/C_Cache_Personnel2'

DROP TABLE "COBRA_CACHE"."C_Cache_Personnel2";

CREATE TABLE "COBRA_CACHE"."C_Cache_Personnel2" (
	"user_name" VARCHAR2(8), 
	"HR_DB_NAME" VARCHAR2(16), 
	"FUNCTIONAL_TITLE" VARCHAR2(40 CHAR), 
	"PERS_CATEGORY" VARCHAR2(1), 
	"LC_STATE" VARCHAR2(10), 
	"LC_DATE" TIMESTAMP (9), 
	"HR_DB_SOURCE" VARCHAR2(40), 
	"HIRE_DATE_C" TIMESTAMP (9), 
	"JOB_HIRE_DATE" TIMESTAMP (9), 
	"TERMINATION_DATE" TIMESTAMP (9), 
	"DIV_BU_CODE" VARCHAR2(13), 
	"DIVISION_CODE" VARCHAR2(6), 
	"DIVISION_DESC" VARCHAR2(64), 
	"BUSINESS_UNIT_CODE" VARCHAR2(6), 
	"BUSINESS_UNIT_DESC" VARCHAR2(64), 
	"SECTOR_CODE" VARCHAR2(2), 
	"ORG_UNIT" VARCHAR2(2), 
	"DEPARTMENT_DESC" VARCHAR2(32 CHAR), 
	"REFERENCE" VARCHAR2(14), 
	"FUNCTION_CODE" VARCHAR2(8), 
	"FUNCTION_DESC" VARCHAR2(64), 
	"COST_CENTER_TYPE" VARCHAR2(8 CHAR), 
	"COST_CENTER_NUMBER" VARCHAR2(10 CHAR), 
	"SUPERVISOR_ID" VARCHAR2(8), 
	"COUNTRY_CODE" VARCHAR2(2), 
	"COUNTRY_NAME" VARCHAR2(25), 
	"WORLD_REGION" VARCHAR2(20), 
	"SITE_CODE" VARCHAR2(4), 
	"SITE_NAME" VARCHAR2(40), 
	"SITE_CODE_EXT" VARCHAR2(8), 
	"SITA_ORG_CODE" VARCHAR2(2), 
	"CD_ID" NUMBER(19,0), 
	"PHONE_COUNTRY_CODE" VARCHAR2(5), 
	"PHONE_AREA_CODE" VARCHAR2(6), 
	"VIP_STATUS" VARCHAR2(20), 
	"OPLEVEL3_CODE" VARCHAR2(40), 
	"OPLEVEL3_DESC" VARCHAR2(64), 
	"OPLEVEL2_CODE" VARCHAR2(40), 
	"OPLEVEL2_DESC" VARCHAR2(64), 
	"OPLEVEL1_CODE" VARCHAR2(40), 
	"OPLEVEL1_DESC" VARCHAR2(64), 
	"EMAIL_DOMAIN" VARCHAR2(50)
);


-- DDL generated by Composite Studio (Fri Nov 27 06:39:02 CET 2015)
-- To cache resource '/shared/Applications/COBRA/RulesDB/role_assignment'
-- To data source '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB'
-- In table '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB/COBRA_CACHE/C_cache_role_assignment0'

DROP TABLE "COBRA_CACHE"."C_cache_role_assignment0";

CREATE TABLE "COBRA_CACHE"."C_cache_role_assignment0" (
"user_name" varchar(40),
"role" varchar(50),
"entity_ref" number(38, 0),
"entity_name" varchar(201),
"entity_eid_attribute_name" varchar(100),
"eid" varchar(50),
"role_id" number(38, 0)
);

CREATE INDEX "COBRA_CACHE"."C_cache_role_assignment0_fk" ON "COBRA_CACHE"."C_cache_role_assignment0"("user_name" asc);


-- DDL generated by Composite Studio (Fri Nov 27 06:39:02 CET 2015)
-- To cache resource '/shared/Applications/COBRA/RulesDB/role_assignment'
-- To data source '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB'
-- In table '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB/COBRA_CACHE/cache_role_assignment1'

DROP TABLE "COBRA_CACHE"."C_cache_role_assignment1";

CREATE TABLE "COBRA_CACHE"."C_cache_role_assignment1" (
"user_name" varchar(40),
"role" varchar(50),
"entity_ref" number(38, 0),
"entity_name" varchar(201),
"entity_eid_attribute_name" varchar(100),
"eid" varchar(50),
"role_id" number(38, 0)
);

CREATE INDEX "COBRA_CACHE"."C_cache_role_assignment1_fk" ON "COBRA_CACHE"."C_cache_role_assignment1"("user_name" asc);


-- DDL generated by Composite Studio (Fri Nov 27 06:39:02 CET 2015)
-- To cache resource '/shared/Applications/COBRA/RulesDB/role_assignment'
-- To data source '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB'
-- In table '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB/COBRA_CACHE/cache_role_assignment2'

DROP TABLE "COBRA_CACHE"."C_cache_role_assignment2";

CREATE TABLE "COBRA_CACHE"."C_cache_role_assignment2" (
"user_name" varchar(40),
"role" varchar(50),
"entity_ref" number(38, 0),
"entity_name" varchar(201),
"entity_eid_attribute_name" varchar(100),
"eid" varchar(50),
"role_id" number(38, 0)
);

CREATE INDEX "COBRA_CACHE"."C_cache_role_assignment2_fk" ON "COBRA_CACHE"."C_cache_role_assignment2"("user_name" asc);

-- DDL generated by Composite Studio (Fri Nov 27 06:45:51 CET 2015)
-- To configuring caching for data source '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB'
-- Using table '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB/COBRA_CACHE/cache_status'
DROP TABLE "COBRA_CACHE"."cache_status";

CREATE TABLE "COBRA_CACHE"."cache_status" (
"clusterid" varchar(40),
"serverid" varchar(80) NOT NULL,
"resourceid" varchar(255) NOT NULL,
"parameters" varchar(255),
"status" char(1) NOT NULL,
"cachekey" number(10, 0) NOT NULL,
"starttime" timestamp(9) NOT NULL,
"finishtime" timestamp(9),
"cleartime" timestamp(9),
"bytes" number(19, 0),
"message" varchar(255),
"bucket" varchar(255),
"incrementalstatus" char(1),
"incrementalmaintenancelevel" varchar(255)
);

-- DDL generated by Composite Studio (Fri Nov 27 06:46:24 CET 2015)
-- To configuring caching for data source '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB'
-- Using table '/shared/Applications/COBRA/DataSources/COBRA_CACHING_DB/COBRA_CACHE/cache_tracking'
DROP TABLE "COBRA_CACHE"."cache_tracking";

CREATE TABLE "COBRA_CACHE"."cache_tracking" (
"clusterid" varchar(40),
"serverid" varchar(80) NOT NULL,
"resourceid" varchar(255) NOT NULL,
"catalog" varchar(255),
"schema" varchar(255),
"table" varchar(255),
"createtime" timestamp(9) 
);

commit;

SPOOL OFF;